name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # هر 5 دقیقه چک می‌کند که ربات در حال اجراست

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Telegram Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: npm start
